# Generated by Django 5.2.5 on 2026-01-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_grade'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grade',
            table='grade',
        ),
    ]
