# Generated by Django 5.2.5 on 2026-01-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_alter_grade_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='names',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
