# Generated by Django 5.2.5 on 2026-01-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_grade_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='names',
        ),
    ]
