# Generated by Django 5.1.6 on 2025-05-12 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enorin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='items_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('enorin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money', to='web_app.enorin')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money', to='web_app.items_types')),
            ],
        ),
    ]
